version: '3.9'

services:

  mini_redis_app:
    container_name: mini_redis_app
    image: redis:6.2-alpine
    restart: always
    ports:
      - '16379:6379'
    command: redis-server --save 20 1
    volumes:
      - ./cache:/data
    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network
  mini_mongo_app:
    container_name: mini_mongo_app
    image: mongo:5.0.14
    depends_on:
      - mini_redis_app
    ports:
      - "17077:27017"
    volumes:
      - ./mongodb-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AUTH=no
      # 以下数据库验证信息暂时不启用
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=app
      - MONGODB_APPLICATION_USER=app
    restart: always

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network
networks: 
  share-network: 
    name: share-network
