version: '3.9'

services:
  app_setting:
    container_name: app_setting
    image: r2day/mini-appearance-api
    volumes:
      - ./config/appearance.env:/app/.env
      - ./data/bbs.json:/app/api/bbs/example.json
    working_dir: "/app/"
    restart: on-failure:5

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network

  store_center_app:
    container_name: store_center_app
    image: r2day/store-center:pro
    volumes:
      - ./config/store_center.env:/app/.env
      - ../image:/app/image
    working_dir: "/app/"
    restart: on-failure:5

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network

  product_center_app:
    container_name: product_center_app
    image: r2day/product-center:pro
    volumes:
      - ./config/product_center.env:/app/.env
    working_dir: "/app/"
    restart: on-failure:5

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network
  order_center_app:
    container_name: order_center_app
    image: r2day/order-center:dev
    volumes:
      - ./config/order_center.env:/app/.env
      - ./logs/order_center/:/app/log  
    working_dir: "/app/"
    restart: on-failure:5

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network
  member_center_app:
    container_name: member_center_app
    image: r2day/member-center:dev
    volumes:
      - ./config/member_center.env:/app/.env
      - ./logs/member/:/app/log/
    working_dir: "/app/"
    restart: on-failure:5

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network
  pay_app:
    container_name: pay_app
    image: r2day/pay-api:dev
    volumes:
      - ./config/pay.env:/app/.env
      - ./config/apiclient_key.pem:/app/config/apiclient_key.pem
      - ./logs/pay-api/:/app/log/
    working_dir: "/app/"
    restart: on-failure:5

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network
  take_out_app:
    container_name: take_out_app
    image: r2day/take-out:dev
    volumes:
      - ./config/take_out.env:/app/.env
      - ./logs/take-out-api/:/app/log/
    working_dir: "/app/"
    restart: on-failure:5
    ports:
      - "31111:8080"

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network

  mini_nginx_app:
    container_name: mini_nginx_app
    image: nginx:1.22.1
    ports:
      - "5580:80"
    depends_on:
      - pay_app
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro

    # 需要使用到该数据库的都需要声明这个网络
    networks:
      - share-network
  fileserver:
    container_name: fileserver
    image: r2day/fileserver
    volumes:
      - ./public:/app/public
    working_dir: "/app/"
    restart: on-failure:5
    ports:
      - "18077:8077"
# 同一个docker-compose.yaml 只需要在末尾声明一次即可
networks:
  share-network:
    name: share-network

